language: cpp
compiler:
  - gcc
  - clang
script:
   mkdir build &&
   mkdir build/Debug && 
   mkdir build/Release &&
   cd build/Debug && 
   cmake -DCMAKE_BUILD_TYPE=Debug ../.. && 
   make &&
   ctest -VV -C Debug &&
   cd ../Release && 
   cmake -DCMAKE_BUILD_TYPE=Release ../.. && 
   make &&
   ctest -VV -C Release &&

